# This file is part of stateplane.
# https://github.com/fitnr/stateplane

# Licensed under the GPLv3 license:
# http://http://opensource.org/licenses/GPL-3.0
# Copyright (c) 2015, Neil Freeman <contact@fakeisthenewreal.org>

language: python

python:
    - 2.7
    - 3.4
    - pypy

install:
    # install python requirements
    - make setup

script:
    # run tests
    - python setup.py test
